### ISSUE TITLE
Poetry SolverProblemError

### ISSUE THREAD

**Issue by rvanruitenbeek** [cjolowicz/cookiecutter-hypermodern-python#1148]
First of all, thanks for writing this amazing template!

I tried to use the template for the creation of a new Python 3.8.5 project. 

Steps I have taken to create the project:
1. `cookiecutter cookiecutter-hypoermodern-python`
2. `poetry lock`

The resulting output I received is:
```
[SolverProblemError]
The current project's Python requirement (>=3.7) is not compatible with some of the required packages Python requirement:
  - isort requires Python >=3.6.1,<4.0

Because isort (5.10.1) requires Python >=3.6.1,<4.0
 and no versions of isort match >5.10.1, isort is forbidden.
So, because some-sample depends on isort (>=5.10.1), version solving failed.
```

Things I tried so far:
- Removing the isort package from the toml --> shifts the problem to other packages
- Removing the lock file before creating the template

**Comment by cjolowicz** [comment]
Hi,

The upper bound on the Python constraint was removed intentionally. See the rationale linked from here: https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/pull/743

It is possible to add dependencies that cap the Python version by adding an environment marker on the requirement. In Poetry this is done using the --python option of the add subcommand. See here for an example: 
https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance/pull/815

**Comment by eyllanesc** [comment]
@cjolowicz I understand what you indicate. I have created #1152 to solve that problem. 

On the other hand, the tool that imports the changes from https://github.com/cjolowicz/cookiecutter-hypermodern-python-instance to this repository has some problems since it is modifying files that it should not modify, so I recommend creating a blacklist that copies but does not deduce templates. In the case of poetry.lock I observe:

https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/b952b2c62eca6fbf589e052a41ee21ac0c0e27b0/%7B%7Bcookiecutter.project_name%7D%7D/poetry.lock#L91
