### ISSUE TITLE
Add yamllint

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/cookiecutter-hypermodern-python#230]
https://github.com/adrienverge/yamllint

**Comment by staticdev** [comment]
@cjolowicz hope you are doing well. Two things:
1) I am working on an [ansible role](https://github.com/staticdev/ansible-role-python-developer) to install cookiecutter-hypermodern-python requirements from [here](https://cookiecutter-hypermodern-python.readthedocs.io/en/2021.1.29/quickstart.html). Maybe we can add it in the future to the Quickstart when it is more stable.
2) It uses yamllint, but I suppose you don't want to add this as a remote pre-commit like [here](https://github.com/staticdev/ansible-role-python-developer/blob/master/.pre-commit-config.yaml) but as a local repo and dev-dependecy, right? I see that only prettier is this way, not really sure why (I guess because you can't `poetry install --dev` it).

PS.: I just entered prettier repo and saw they changed address again to `https://github.com/pre-commit/mirrors-prettier` =/

**Comment by cjolowicz** [comment]
@staticdev Sorry for the late response.

> 1. I am working on an [ansible role](https://github.com/staticdev/ansible-role-python-developer) to install cookiecutter-hypermodern-python requirements from [here](https://cookiecutter-hypermodern-python.readthedocs.io/en/2021.1.29/quickstart.html). Maybe we can add it in the future to the Quickstart when it is more stable.

Thanks for working on this! PR welcome.

> 2. It uses yamllint, but I suppose you don't want to add this as a remote pre-commit like [here](https://github.com/staticdev/ansible-role-python-developer/blob/master/.pre-commit-config.yaml) but as a local repo and dev-dependecy, right? I see that only prettier is this way, not really sure why (I guess because you can't `poetry install --dev` it).

I'm closing this for now because Prettier already lints YAML.

We use local hooks for Python linters only, because we can add them as development dependencies. They are installed in the pre-commit Nox session. Prettier is a regular pre-commit hook managed by pre-commit because it's not a Python dependency.

> PS.: I just entered prettier repo and saw they changed address again to `https://github.com/pre-commit/mirrors-prettier` =/

This was fixed, thanks again.
