### ISSUE TITLE
New focus on pre-commit

### ISSUE THREAD

**Issue by paw-lu** [cjolowicz/cookiecutter-hypermodern-python#316]
Hi @cjolowicz , love the work done here. This is one of my favorite new projects!

Just some thoughts/questions on the latest changes—specifically the new focus on pre-commit. It seems to cause a few sticking points for me:

- Project dependencies are no longer all specified in one file
- `.pre-commit-config.yaml` is not as easily upgraded by tools such as Dependabot, Poetry, pip, etc
- The environment is "fractured" (some of it defined in `pyproject.toml`, some in the pre-commit environment). A "canonical" environment is no longer defined, which causes some issues with other tools.
    - The issue I ran up against was using VS Code. Typically in VS Code I'll select a canonical environment (usually the Poetry venv) to power editor features—such as discovering tests, powering the linter UI, autoformatting, and running scripts. This seems no longer possible with the current setup.
- Having nox just call pre-commit obfuscates some of the options. A lot of functionality is "hidden" behind pre-commit (autoformatting, linting, checking), I like the functionality of calling `nox --list` to see the tasks available, and having each nox session specified for one task.
- Some flake8 plugins need a little more integration with the library and its dependencies (I'm thinking of extensions like flake8-mypy, flake8-isort). Adding such plugins is not straightforward in the current pre-commit method.
- It's currently not possible (I think?) to lint in multiple Python versions

_Edit: one more_

- Pre-commit's `--all-files` still ignores uncommitted files. So you won't be able to lint or format a file until committed.

You've obviously thought about this way more than I have, so I was generally curious why there was a move away from centralizing around `pyproject.toml`.

Thanks!

**Comment by cjolowicz** [comment]
Thank you @paw-lu for the thoughtful comment. Your concerns resonate well with me. Some of these drawbacks were on my mind when I considered the pros and cons of this move. You also add new points that I haven't considered, such as editor integration. I'm definitely open to finding a better solution for integrating pre-commit into this setup.

Let me first sum up the changes that lead to the status quo:

- Nox sessions for flake8 and black were removed (#235, #236)
- Poetry dev dependencies on black, flake8, and flake8 extensions were dropped
- repository-local hooks (using `poetry run`) for flake8 and black were replaced by their official pre-commit hooks (#231)
- Nox session for pre-commit was added (#233) [this is a bit orthogonal though]

The reasons for this were the following:

- Remove friction for people already familiar with the pre-commit ecosystem.
- Avoid confusion for beginners who would get a pre-commit config unlike those shown in all the tutorials.
- Remove the duplication and boilerplate associated with repository-local hooks (essentially, any pre-commit hook needs to be copy-pasted, prepending `poetry run` to the command-line and switching the language to `system`). Some hooks were already non-local (`pre-commit-hooks`).
- Use battle-tested official hooks instead of rolling our own.
- Do not constrain package dependencies by linter requirements. With a rich linter suite,
  conflicts with dependencies or Python requirements of the main package are more likely.
- Avoid the complexity coming from integrating pre-commit with Nox and Poetry.
- Do not require an initialized and fully installed Poetry environment for running pre-commit hooks. You had to first run `poetry install` to be able to run pre-commit.
- Stop trying to hack features into tools that they don't yet have ;-) Sometimes it's better to live with the limitations of your tools, than hacking together fragile workarounds. Limitations like these:
  - pre-commit dependency upgrades cannot be easily automated.
  - pre-commit requires boilerplate to run hooks against multiple Python versions.
  - Poetry does not have multiple dependency sets.
- Linting on older Python versions is arguably less important if you have a cross-Python mypy session in Nox.

**Comment by paw-lu** [comment]
@cjolowicz . Thank you so much for the response. As usual, your comments are so well thought out and communicated! It took me a while to respond to this as I was exploring alternative implementations, but I honestly can't think of any reasonable approach that would satisfy all concerns.

> Stop trying to hack features into tools that they don't yet have ;-) Sometimes it's better to live with the limitations of your tools, than hacking together fragile workarounds.

This is so well said 🙂. I wholeheartedly agree with this statement. It is not worth hacking together questionable methods to stretch tools beyond what they are primarily meant to do.

Honestly, as I read through your points, it seems to me that you made the right call. As I weigh the points you listed against my own, the benefits of the changes seem to outweigh the cons. I do think it was a good choice to move away from local pre-commit hooks.

I am honestly a little bummed that you lose both editor integration and dependency management through Poetry/Dependabot for the linters and formatters, but I think the changes you made are for the best given the circumstances.

Again, thanks for listening to my thoughts!

**Comment by paw-lu** [comment]
Also congrats on being featured in PyCoder's Weekly!
