### ISSUE TITLE
[Query] Rational for reinstalling package in noxfile.py

### ISSUE THREAD

**Issue by e0lithic** [cjolowicz/cookiecutter-hypermodern-python#348]
Hi,

In noxfile `install_package` function, you are reinstalling the package through the generated wheel. I would love to know what was the rational for reinstalling the package using the wheel and why the original version mentioned in your blog in the form of ` session.run("poetry", "install", "--no-dev", external=True)` has not been used.

Thanks

**Comment by cjolowicz** [comment]
There are two reasons for this (see #3):

- When invoked with `install --no-dev`, Poetry _uninstalls_ development dependencies, for example pytest in the tests session. This unfortunate behavior on Poetry's side (see https://github.com/python-poetry/poetry/issues/513#issuecomment-491582288) means that the development dependencies need to be reinstalled on every Nox run, even when reusing environments with `nox -r`.

- Running tests against the installed package is a good practise, because you're testing what your users get when installing from PyPI. With `poetry install`, you get an editable install, and there is no way to opt out of that (https://github.com/python-poetry/poetry/issues/1382). This means that you're not testing against the package you are going to distribute, but against your working directory, which can differ from the package due to local modifications or for more obscure reasons.

**Comment by e0lithic** [comment]
Thanks for the insights.
