### ISSUE TITLE
Add docs-build to nox.options.sessions

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cookiecutter-hypermodern-python#461]
Since there is no `docs` session on nox.options.sessions, broken documentation can easily pass unnoticed. On the other hand, by just adding `docs` to nox.options.sessions it would serve the documentation as a website everytime, which is not the behavior I would expect also.

For me `nox` command should build but not serve the documentation to bulletproof our checks. One alternative could be adding a new `docs-build` session to nox that just builds it. I don't have much knowledge about nox but current `docs` session could call `docs-build` session or maybe there is a smarter way to parameterize the `docs` session not to serve.

What are your thoughts on that?

**Comment by cjolowicz** [comment]
I think you're right. We should split the `docs` session into two, and not rely on `session.interactive`. The pure `sphinx` session can then be listed in `nox.options.sessions`. By contrast, the session running `sphinx-autobuild` must be invoked explicitly by the user.

Also, I think the naming you suggest is right on. The short name `docs` should invoke `sphinx-autobuild`, the friendly interactive version. The other session can have a less intuitive name, as it's only important for batch jobs, so `docs-build` is a good fit. The GA workflow needs to be updated to run `docs-build` instead of `docs`.

**Comment by staticdev** [comment]
Yes, I will try to get it done for next release.
