### ISSUE TITLE
Refactored nox / mypy settings

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/cookiecutter-hypermodern-python#520]
Hi @cjolowicz, 

I would like you to take a look at this PR https://github.com/staticdev/toml-validator/pull/159/files I received for a project using this cookiecutter. And see if there is something you can use here.

Kind regards,

@staticdev

**Comment by staticdev** [comment]
Also this resulted in the discussion here https://github.com/pytest-dev/pytest-mock/pull/205

**Comment by cjolowicz** [comment]
Thanks for the heads up! Unfortunately, I'm missing the context here. Those are a lot of changes, and from the PR description it is not entirely clear what the motivation for them was. Apparently there was some discussion prior to that PR, but it's not linked.

FWIW I prefer to list the individual mypy settings instead of using `strict`. I find this more explicit and reliable, as `strict` can change over time. The additional mypy settings ([disallow_any_unimported], [disallow_any_decorated]) are not a part of `strict` which is why they are not part of this project template. I'm open to including them if you would like to make a case for doing so.

[disallow_any_decorated]: https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-disallow-any-decorated
[disallow_any_unimported]: https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-disallow-any-unimported

As for the Nox types, it's not clear to me why the types distributed with Nox are not sufficient.

**Comment by cjolowicz** [comment]
Closing this, we're now using `strict` instead of individual settings (#869, released in 2021.4.15).
