### ISSUE TITLE
Integrating your template into cookietemple

### ISSUE THREAD

**Issue by Zethson** [cjolowicz/cookiecutter-hypermodern-python#720]
Dear everyone here,

I just discovered your template and love it.
We at cookietemple (https://github.com/cookiejar/cookietemple/) were looking to move our cli-python template to poetry and nox already anyways. The rest of your features we pretty much already cover.

Would you guys be up to integrating your template into cookietemple (replacing the current cli-python) template?
We could then maintain it over at cookietemple together with all other templates.

We can also discuss this further in the cookietemple discord https://discord.com/invite/PYF8NUk if you guys want to.

What are your thoughts?

**Comment by Zethson** [comment]
cookietemple also provides a couple of things that your template currently does not

1. We cookiecutter the license (choose from 10+ options)
2. Master branch protection
3. Push your template automatically to Github Accounts!
4. Template syncing! We change the template at cookietemple and release it -> every projects gets a pull request with only the template changes. This allows us to keep all projects at the hightest and latest standards
5. Read the Docs css style
6. Much more....

**Comment by Zethson** [comment]
I've actually started doing just that:

https://github.com/cookiejar/cookietemple/pull/595

**Comment by Zethson** [comment]
@paolodina @oncleben31 we just released version 1.3.0 which contains a slight adaption of this template. Feel free to try it out and to use it!

**Comment by cjolowicz** [comment]
Hello @Zethson,

Let me just say that your way of approaching this, while presumably well-intentioned, was not the most tactful. You may have heard of *fork etiquette*. Asking me to help you copy my codebase into your repository because it's somehow in my own interest, and then just going ahead after less than a day of waiting... oh well.

But in the end, I'm glad you like the template, and I encourage people to create their own customized version of it.

May I just kindly ask two things of you?

1. This project deliberately uses a simple, permissive [license](https://github.com/cjolowicz/cookiecutter-hypermodern-python/blob/main/LICENSE.rst), but that license does require you to include it in your adaptation of this template:
   
   > The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

2. The template uses a non-standard way of integrating pre-commit with Nox and Poetry. The documentation [goes into great length](https://cookiecutter-hypermodern-python.readthedocs.io/en/2021.3.14/guide.html#linting-with-pre-commit) in explaining the advantages and disadvantages of this method, and how to opt out of it. Please, at the very least, explain to your users that this method is not officially supported by the pre-commit project. Any issues with it should be reported on your repository, not upstream.

Finally, if you find anything in the template that could be improved (I'm sure you have, and will continue to do so), any issues or PRs here will be greatly appreciated.

**Comment by Zethson** [comment]
Dear @cjolowicz,

I perfectly understand you reasoning and would like to apologize for my approach.
I've included the license to the corresponding code section. Every project created from this template also already includes a link to your repository.

We will ensure that issues with the template will be reported on our repository. Moreover, any relevant changes that we consider positive for the template will be contributed back to your project.

Cheers.

**Comment by cjolowicz** [comment]
Thanks @Zethson accepted and appreciated :)
