### ISSUE TITLE
Pre-commit hooks make changes in CI

### ISSUE THREAD

**Issue by romesco** [cjolowicz/cookiecutter-hypermodern-python#735]
First of all, I just want to say, I love this project. It's very thoughtful, extremely well documented, and encourages discussion about an otherwise very opinionated and 'hand-wavy' aspect of writing good code - development process. I really like the idea of version controlling this and constantly reevaluating.

I'm noticing that a side-effect of the pre-commit workflow owning the entirety of linting seems to be that the formatters make changes during CI. Ideally, if you've run pre-commit locally, this shouldn't happen, but I suppose it can be confusing to newer contributors to a repo. When I first learned about formatters in CI, I actually thought they would automatically fix my code after I pushed it (which comes with its own issues) 😆.

This seems to diverge from your [comments here about keeping black and linting as separate sessions](https://cjolowicz.github.io/posts/hypermodern-python-03-linting/).

It's definitely not a dealbreaker, but I wanted to make sure I wasn't configuring something incorrectly.

**Comment by cjolowicz** [comment]
Thanks for the feedback :green_heart: 

> a side-effect of the pre-commit workflow owning the entirety of linting seems to be that the formatters make changes during CI

They do, but the modifications are thrown away after the CI run, not pushed back onto the contributor's branch, like you say. Personally, I find this *less* confusing :wink: What would you suggest that we should do here? Do you think the documentation could be improved?

> This seems to diverge from your comments here about keeping black and linting as separate sessions.

Yes it does :upside_down_face: But that's because `pre-commit` allows for a different approach, where changes are staged by the developer before running the linters, and automatic fixes are applied to the working tree. Also people generally expect `pre-commit` to apply automatic fixes, so this is less of a surprise than when you're running a `lint` Nox session.

> I wanted to make sure I wasn't configuring something incorrectly.

Doesn't look like it.

**Comment by cjolowicz** [comment]
Closing for now, let me know if you have any further questions :+1:
